python=123
english=456
c=789
print("python="+str(python)+"english="+str(english)+"c="+str(c)+"\n")
print("python<english的结果是："+str(python<english))
print("python>english的结果是："+str(python>english))
print("python==english的结果是："+str(python==english))
print("python!=english的结果是："+str(python!=english))
print("python<=english的结果是："+str(python<=english))
print("python>=c的结果是："+str(python>=c))
